package utils {
	public class LangUtils {
		private static var three:Array = new Array("aar","abk","ave","afr","aka","amh","arg","ara","asm","ava","aym","aze","bak","bel","bul","bih","bis","bam","ben","bod","bre","bos","cat","che","cha","cos","cre","ces","chu","chv","cym","dan","deu","div","dzo","ewe","ell","eng","epo","spa","est","eus","fas","ful","fin","fij","fao","fra","fry","gle","gla","glg","grn","guj","glv","hau","heb","hin","hmo","hrv","hat","hun","hye","her","ina","ind","ile","ibo","iii","ipk","ido","isl","ita","iku","jpn","jav","kat","kon","kik","kua","kaz","kal","khm","kan","kor","kau","kas","kur","kom","cor","kir","lat","ltz","lug","lim","lin","lao","lit","lub","lav","mlg","mah","mri","mkd","mal","mon","mar","msa","mlt","mya","nau","nob","nde","nep","ndo","nld","nno","nor","nbl","nav","nya","oci","oji","orm","ori","oss","pan","pli","pol","pus","por","que","roh","run","ron","rus","kin","san","srd","snd","sme","sag","sin","slk","slv","smo","sna","som","sqi","srp","ssw","sot","sun","swe","swa","tam","tel","tgk","tha","tir","tuk","tgl","tsn","ton","tur","tso","tat","twi","tah","uig","ukr","urd","uzb","ven","vie","vol","wln","wol","xho","yid","yor","zha","zho","zul")
		private static var name:Array = new Array("Afar","Abkhazian","Avestan","Afrikaans","Akan","Amharic","Aragonese","Arabic","Assamese","Avaric","Aymara","Azerbaijani","Bashkir","Belarusian","Bulgarian","Bihari languages","Bislama","Bambara","Bengali","Tibetan","Breton","Bosnian","Catalan","Chechen","Chamorro","Corsican","Cree","Czech","Church Slavic","Chuvash","Welsh","Danish","German","Divehi","Dzongkha","Ewe","Greek","English","Esperanto","Spanish","Estonian","Basque","Persian","Fulah","Finnish","Fijian","Faroese","French","Western Frisian","Irish","Gaelic","Galician","Guarani","Gujarati","Manx","Hausa","Hebrew","Hindi","Hiri Motu","Croatian","Haitian","Hungarian","Armenian","Herero","Interlingua","Indonesian","Interlingue","Igbo","Sichuan Yi","Inupiaq","Ido","Icelandic","Italian","Inuktitut","Japanese","Javanese","Georgian","Kongo","Kikuyu","Kuanyama","Kazakh","Kalaallisut","Central Khmer","Kannada","Korean","Kanuri","Kashmiri","Kurdish","Komi","Cornish","Kirghiz","Latin","Luxembourgish","Ganda","Limburgan","Lingala","Lao","Lithuanian","Luba-Katanga","Latvian","Malagasy","Marshallese","Maori","Macedonian","Malayalam","Mongolian","Marathi","Malay","Maltese","Burmese","Nauru","Bokmål","Ndebele","Nepali","Ndonga","Dutch","Norwegian Nynorsk","Norwegian","Ndebele"," South","Navajo","Chichewa","Occitan","Ojibwa","Oromo","Oriya","Ossetian","Panjabi","Pali","Polish","Pushto","Portuguese","Quechua","Romansh","Rundi","Romanian","Russian","Kinyarwanda","Sanskrit","Sardinian","Sindhi","Northern Sami","Sango","Sinhala","Slovak","Slovenian","Samoan","Shona","Somali","Albanian","Serbian","Swati","Sotho"," Southern","Sundanese","Swedish","Swahili","Tamil","Telugu","Tajik","Thai","Tigrinya","Turkmen","Tagalog","Tswana","Tonga","Turkish","Tsonga","Tatar","Twi","Tahitian","Uighur","Ukrainian","Urdu","Uzbek","Venda","Vietnamese","Volapük","Walloon","Wolof","Xhosa","Yiddish","Yoruba","Zhuang","Chinese","Zulu");
		public static function getName(value:String):String {
			var ret:String="";
			if(three.indexOf(value.toLowerCase()) > -1)
				ret = name[three.indexOf(value.toLowerCase())];
			return ret;
		}
	}
}